### ISSUE TITLE
Post a doubly linked list code

### ISSUE THREAD

**Issue by Souvikray** [stephengrice/youtube#1]
I have understood your singly linked list code and it clean and clear and it would be helpful if you could post a double linked list code.

**Comment by stephengrice** [comment]
Hey, thanks a bunch. I'm really glad the code helped you! I'm hoping to start on some more data structure this weekend, so I'll make sure doubly linked list one of them.

**Comment by stephengrice** [comment]
I did some research on the topic and posted some code for Doubly Linked List. It may not be perfect, but let me know if it helps. [https://github.com/stephengrice/youtube/blob/master/LinkedList/doubly_linked_list.py](The code is here.)

**Comment by Souvikray** [comment]
Hey thanks a lot!
